// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3fMLM4DprNcev4YYuYDj41CqKcdli84g',
    appId: '1:458450081375:web:d0ac9a2b6c99bedb3cadea',
    messagingSenderId: '458450081375',
    projectId: 'form-fit-learner-c8f18',
    authDomain: 'form-fit-learner-c8f18.firebaseapp.com',
    storageBucket: 'form-fit-learner-c8f18.firebasestorage.app',
    measurementId: 'G-VY0QPFMG0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo8wMAbHXJ7QFTabFM35Er_a_0gdZXwWk',
    appId: '1:458450081375:android:a275f3e3f91f189e3cadea',
    messagingSenderId: '458450081375',
    projectId: 'form-fit-learner-c8f18',
    storageBucket: 'form-fit-learner-c8f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUp-39NjONMNk7-cIgJzlcqmY8geD0j8',
    appId: '1:458450081375:ios:774aa1991cd5ad273cadea',
    messagingSenderId: '458450081375',
    projectId: 'form-fit-learner-c8f18',
    storageBucket: 'form-fit-learner-c8f18.firebasestorage.app',
    iosBundleId: 'com.formfit.formFitApp',
  );
}
